; (define withdraw
;   (let ((balance 100))
;     (lambda (amount)
;       (if (<= amount balance)
;           (begin (set! balance (- balance amount))
;                  balance)
;           "insufficient funds"))))
; (withdraw 90)
; (withdraw 11)
(define (make-account balance)
  (define (withdraw amount)
    (if (<= amount balance)
        (begin (set! balance (- balance amount))
               balance)
        "insufficient funds"))
  (define (deposit amount)
    (if (> amount 0)
        (begin (set! balance (+ balance amount))
               balance)
        "insufficient funds"))
  (define (dispatch m)
    (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown requests -- MAKE-ACCOUNT" m))))
  dispatch)
(define acc (make-account 100))
((acc 'withdraw) 70)
((acc 'deposit) 120)
