;ex3.3
;ex3.4
(define (make-account balance password)
  (define wrong-try 0)
  (define (call-the-cops)
    "Called the cops.")
  (define (withdraw amount)
    (if (<= amount balance)
        (begin (set! balance (- balance amount))
               balance)
        "insufficient funds"))
  (define (deposit amount)
    (if (> amount 0)
        (begin (set! balance (+ balance amount))
               balance)
        "insufficient funds"))
  (define (dispatch input-password m)
    (if (eq? input-password password)
        (begin
          (set! wrong-try 0)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit) deposit)
                (else (error "Unknown requests -- MAKE-ACCOUNT" m))))
        (lambda (dummy-amount)
          (set! wrong-try (+ wrong-try 1))
          (if (< wrong-try 7)
              wrong-try
              (call-the-cops)))))
  dispatch)
(define acc (make-account 100 'a-sample-password))
((acc 'a-sample-password 'withdraw) 700)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-password 'deposit) 120)
((acc 'a-sample-passwor 'withdraw) 70)
((acc 'a-sample-passwor 'withdraw) 70)
