;ex3.2
(define (make-monitored proc)
  (define counter 0)
  (define (how-many-calls?) counter)
  (define (reset-count)
    (begin ((set! counter 0)
            counter)))
  (define (depatch . params)
    (cond ((eq? (car params) 'how-many-calls?) (how-many-calls?))
          ((eq? (car params) 'reset-count) (reset-count))
          (else
            (set! counter (+ counter 1))
            (apply proc params))))
  depatch)
(define msqrt (make-monitored sqrt))
(msqrt 9)
(msqrt 16)
(msqrt 'how-many-calls?)
(msqrt 'reset-count)
(msqrt 36)
(msqrt 'how-many-calls?)
